"""Calibration engine for confluence weights and position sizing.

Uses historical factor expectancy and lift to adjust scoring weights,
and applies fractional Kelly Criterion to optimize risk exposure.
"""

from __future__ import annotations

import pandas as pd
from smc_quant import DEFAULT_CONFLUENCE_WEIGHTS


def calibrate_confluence_weights(
    attribution_report: dict,
    base_weights: dict[str, int] | None = None,
) -> dict:
    """Calibrate confluence weights based on single-factor lift and expectancy.
    
    Factors with negative expectancy are scaled down or disabled (set to 0).
    Factors with high positive lift are scaled up.
    
    Args:
        attribution_report: Dict generated by generate_attribution_report().
        base_weights: Optional starting weights dictionary.
        
    Returns:
        Dict containing:
          - 'proposed_weights': Adjusted weight mapping.
          - 'changes': List of description strings for the calibration log.
    """
    weights = dict(base_weights or DEFAULT_CONFLUENCE_WEIGHTS)
    factors = attribution_report.get("factors") or {}
    changes = []
    
    for factor, metrics in factors.items():
        if factor not in weights:
            continue
            
        base = weights[factor]
        exp_r = metrics.get("expected_r", 0.0)
        lift = metrics.get("lift", 1.0)
        count = metrics.get("count", 0)
        
        # Only calibrate if we have at least 5 samples for the factor to prevent noise fitting
        if count >= 5:
            if exp_r < 0:
                # Negative expectancy: set weight to 0 to disable
                weights[factor] = 0
                changes.append(f"Disabled {factor} (weight {base} -> 0) due to negative expectancy ({exp_r:.3f}R)")
            else:
                # Adjust based on lift (clamp multiplier between 0.5 and 2.0)
                adj_mult = max(0.5, min(2.0, lift))
                new_w = int(round(base * adj_mult))
                new_w = max(1, min(5, new_w))  # Keep weights between 1 and 5
                
                if new_w != base:
                    weights[factor] = new_w
                    changes.append(f"Adjusted {factor} (weight {base} -> {new_w}) based on lift ({lift:.2f})")
                    
    return {
        "proposed_weights": weights,
        "changes": changes,
    }


def calculate_kelly_fraction(
    win_rate: float,
    avg_win_pnl: float,
    avg_loss_pnl: float,
    fraction: float = 0.25,  # Quarter Kelly by default
    min_cap: float = 0.005,  # 0.5% risk cap
    max_cap: float = 0.030,  # 3.0% risk cap
) -> float:
    """Calculate the Kelly Criterion sizing fraction with conservative capping.
    
    f* = (p * b - q) / b
    where p is win rate, q is loss rate, b is payoff ratio (avg_win / avg_loss).
    
    Args:
        win_rate: Strategic win rate (0.0 to 1.0).
        avg_win_pnl: Mean positive trade return or pnl.
        avg_loss_pnl: Mean negative trade return or pnl (should be positive value).
        fraction: Scale down factor (e.g. 0.25 for 1/4 Kelly).
        min_cap: Minimum allowed risk fraction.
        max_cap: Maximum allowed risk fraction.
        
    Returns:
        Recommended risk fraction per trade (e.g. 0.015 for 1.5% risk).
    """
    if win_rate <= 0.0 or win_rate >= 1.0:
        return min_cap
        
    loss_rate = 1.0 - win_rate
    abs_loss = abs(avg_loss_pnl)
    
    if abs_loss <= 0.0001:
        return min_cap
        
    payoff_ratio = abs(avg_win_pnl) / abs_loss
    if payoff_ratio <= 0.01:
        return min_cap
        
    # Standard Kelly
    f_star = (win_rate * payoff_ratio - loss_rate) / payoff_ratio
    
    if f_star <= 0:
        return min_cap
        
    # Apply fractional scaling and cap
    scaled = f_star * fraction
    return float(max(min_cap, min(max_cap, scaled)))
