"""Weekly learning-loop digest → Obsidian markdown.

Audit fix C3. edge_decay writes single-event notes; we have no
weekly roll-up. Operators (i.e. me) need a Sunday-night summary:
how many trades, E[R], top-winners per cluster, weight drift,
whether the loop applied a sweep.

Produces a markdown file at
``<vault>/SMC/Digests/<YYYY>-W<NN>.md`` and returns the body string.
Idempotent: re-running for the same ISO week overwrites the file
(weekly cron-friendly).
"""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional


def _parse_ts(value) -> Optional[datetime]:
    if not value:
        return None
    try:
        ts = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        if ts.tzinfo is None:
            ts = ts.replace(tzinfo=timezone.utc)
        return ts
    except Exception:
        return None


def _iso_week_window(now: Optional[datetime] = None) -> tuple[datetime, datetime, str]:
    now = now or datetime.now(timezone.utc)
    # ISO week: Monday is day 1
    monday = now - timedelta(days=now.weekday())
    monday = monday.replace(hour=0, minute=0, second=0, microsecond=0)
    sunday = monday + timedelta(days=7) - timedelta(microseconds=1)
    iso_year, iso_week, _ = monday.isocalendar()
    return monday, sunday, f"{iso_year}-W{iso_week:02d}"


def build_weekly_digest(
    records: list[dict],
    *,
    now: Optional[datetime] = None,
    top_n_clusters: int = 5,
) -> dict:
    """Return ``{"label": ..., "markdown": ...}`` for the current ISO week."""
    monday, sunday, label = _iso_week_window(now)
    week_records = []
    for r in records or []:
        ts = _parse_ts(r.get("entry_time"))
        if ts and monday <= ts <= sunday:
            week_records.append(r)

    resolved = [r for r in week_records
                  if r.get("outcome") not in (None, "pending")
                  and r.get("r_multiple") is not None]
    n_total = len(week_records)
    n_resolved = len(resolved)
    rs = [float(r["r_multiple"]) for r in resolved if r.get("r_multiple") is not None]
    e_R = (sum(rs) / len(rs)) if rs else 0.0
    win_rate = (sum(1 for x in rs if x > 0) / len(rs)) if rs else 0.0

    # Per-cluster mean R, top winners + losers
    by_cluster: dict[tuple, list[float]] = defaultdict(list)
    for r in resolved:
        key = (str(r.get("model") or "?"), str(r.get("symbol") or "?"),
               str(r.get("interval") or "?"))
        by_cluster[key].append(float(r["r_multiple"]))
    cluster_stats = [
        {"cluster": k, "n": len(v), "mean_R": round(sum(v) / len(v), 4)}
        for k, v in by_cluster.items() if len(v) >= 1
    ]
    winners = sorted(cluster_stats, key=lambda c: -c["mean_R"])[:top_n_clusters]
    losers = sorted(cluster_stats, key=lambda c: c["mean_R"])[:top_n_clusters]

    md_lines = [
        "---",
        f"title: SMC Weekly Digest {label}",
        f"week_start: {monday.isoformat()}",
        f"week_end: {sunday.isoformat()}",
        "tags: [smc, digest, learning]",
        "---",
        "",
        f"# Week {label}",
        "",
        f"- Total trades this week: **{n_total}**",
        f"- Resolved: **{n_resolved}**",
        f"- E[R]: **{round(e_R, 3)}R**",
        f"- Win rate: **{round(win_rate * 100, 1)}%**",
        "",
        "## Top cluster winners",
    ]
    if winners:
        md_lines.append("| Model | Symbol | Interval | N | E[R] |")
        md_lines.append("|---|---|---|---|---|")
        for w in winners:
            m, s, i = w["cluster"]
            md_lines.append(f"| {m} | {s} | {i} | {w['n']} | {w['mean_R']} |")
    else:
        md_lines.append("_no resolved trades this week_")
    md_lines.append("")
    md_lines.append("## Top cluster losers")
    if losers:
        md_lines.append("| Model | Symbol | Interval | N | E[R] |")
        md_lines.append("|---|---|---|---|---|")
        for w in losers:
            m, s, i = w["cluster"]
            md_lines.append(f"| {m} | {s} | {i} | {w['n']} | {w['mean_R']} |")
    else:
        md_lines.append("_no resolved trades this week_")
    md_lines.append("")
    md_lines.append("_Auto-generated by learning.weekly_digest._")
    return {"label": label, "markdown": "\n".join(md_lines),
            "n_total": n_total, "n_resolved": n_resolved,
            "mean_R": round(e_R, 4), "win_rate": round(win_rate, 4)}


def write_weekly_digest(
    records: list[dict],
    vault: str,
    *,
    now: Optional[datetime] = None,
) -> dict:
    """Build and write the digest to ``<vault>/SMC/Digests/<label>.md``."""
    out = build_weekly_digest(records, now=now)
    notes_dir = Path(vault) / "SMC" / "Digests"
    notes_dir.mkdir(parents=True, exist_ok=True)
    fp = notes_dir / f"{out['label']}.md"
    fp.write_text(out["markdown"], encoding="utf-8")
    out["path"] = str(fp)
    return out
